import Head from 'next/head'
import { Sidebar } from '../components/Sidebar'
import React, { useEffect, useState } from 'react'
import axios from 'axios'
import { Cart } from '../components/Cart'
import { log } from 'next/dist/server/typescript/utils'
import { Header } from '../components/Header'

export default function Home() {
  const [companies, setCompany] = useState([])
  const [filtered, setFiltered] = useState(companies)

  useEffect(() => {
    try {
      const fetchData = async () => {
        const response = await axios(
          'https://test-api.biterika.team/v1/campaigns'
        )
        setCompany(response.data.campaigns)
      }
      fetchData()
    } catch (error) {
      console.log(error)
    }
  }, [])

  const handlerFilterCategory = state => {
    if (state === 'all') {
      setFiltered(companies)
    }
    if (state === 'in_progress') {
      const newStatus = [...companies].filter(el => el.state === state)
      setFiltered(newStatus)
    }
    if (state === 'moderation') {
      const newStatus = [...companies].filter(el => el.state === state)
      setFiltered(newStatus)
    }
    if (state === 'paused') {
      const newStatus = [...companies].filter(el => el.state === state)
      setFiltered(newStatus)
    }
  }

  useEffect(() => {
    setFiltered(companies)
  }, [companies])

  return (
    <div>
      <Head>
        <title>Cabinet</title>
        <meta name='description' content='Generated by create next app' />
        <link
          rel='stylesheet'
          href='https://cdn.jsdelivr.net/npm/choices.js/public/assets/styles/choices.min.css'
        />
        <link
          media='all'
          rel='stylesheet'
          href='https://static.biterika.team/brobooster/assets/css/vendor.min.css'
        />
        <link
          media='all'
          rel='stylesheet'
          href='https://cdn.jsdelivr.net/npm/intl-tel-input@16.0.2/build/css/intlTelInput.css'
        />
        <link
          media='all'
          rel='stylesheet'
          href='https://static.biterika.team/brobooster/assets/css/styles.min.css'
        />
      </Head>
      <div className='main flex-column'>
        <Header />
        <section className='lk-section flex-column flex-auto'>
          <div className='container flex-column flex-auto'>
            <div className='lk-wrapper full'>
              <Sidebar />
              <div className='lk-content flex-column flex-auto'>
                <div className='section-head'>
                  <h1 className='section-title mr-25 js-title'>Кампании</h1>
                  <a
                    href='new-campaing.html'
                    className='btn-main desktop-none ml-auto'
                  >
                    <svg className='icon icon-medium'>
                      <use xmlnsXlink='#add-24'></use>
                    </svg>
                  </a>
                </div>
                <div className='filter-tabs js-tabs mt-2 mt-lg-25'>
                  <div className='filter-tabs__scroll scroll-none'>
                    <ul className='filter-tabs__header flex-auto js-tabs-buttons mb-15 mb-md-2 mb-lg-25'>
                      <li
                        onClick={() => handlerFilterCategory('all')}
                        data-tab='all'
                        className='filter-tabs__btn-circle active'
                      >
                        Все
                      </li>
                      <li
                        onClick={() => handlerFilterCategory('in_progress')}
                        data-tab='1'
                        className='filter-tabs__btn-circle'
                      >
                        В работе
                      </li>
                      <li data-tab='2' className='filter-tabs__btn-circle'>
                        Ожидают начала
                      </li>
                      <li
                        onClick={() => handlerFilterCategory('paused')}
                        data-tab='3'
                        className='filter-tabs__btn-circle'
                      >
                        Приостановлены
                      </li>
                      <li
                        onClick={() => handlerFilterCategory('moderation')}
                        data-tab='4'
                        className='filter-tabs__btn-circle'
                      >
                        На модерации
                      </li>
                      <li data-tab='5' className='filter-tabs__btn-circle'>
                        Завершенные
                      </li>
                    </ul>
                  </div>
                  <div className='table'>
                    <div className='table__md-wrap'>
                      <div className='table__head table__head--col-8 is-tablet mb-15 mb-lg-2'>
                        <div className='table__row'>
                          <div className='table__col'>
                            <span className='small-xl-text color-sub'>
                              Кампания
                            </span>
                          </div>
                          <div className='table__col widescreen-lg'>
                            <span className='small-xl-text color-sub'>
                              Креативы
                            </span>
                          </div>
                          <div className='table__col widescreen-lg'>
                            <span className='small-xl-text color-sub'>
                              Место проведения
                            </span>
                          </div>
                          <div className='table__col'>
                            <span className='small-xl-text color-sub'>
                              Локации
                            </span>
                          </div>
                          <div className='table__col'>
                            <span className='small-xl-text color-sub'>
                              Транспорт
                            </span>
                          </div>
                          <div className='table__col'>
                            <span className='small-xl-text color-sub'>
                              Показ
                            </span>
                          </div>
                          <div className='table__col'>
                            <span className='small-xl-text color-sub'>
                              Бюджет
                            </span>
                          </div>
                          <div className='table__col'></div>
                        </div>
                      </div>
                      <div className='table__body filter-tabs__content'>
                        <Cart filtered={filtered} />
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>
    </div>
  )
}
